name: Create Github Release

on:
  push:
    tags: "v*"

jobs:
  create-release:
    runs-on: windows-latest
    
    strategy:
      matrix:
       arch: [x64, x86]

    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v5
        with:
          name: "WindowsBuild-${{ matrix.arch }}"
          path: "artifact"

      - name: Create Release for Windows (${{ matrix.arch }})
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifact/WindowsBuild-*"
          name: ParseLegacy ${{ github.ref_name }} for Windows ${{ matrix.arch }}
          tag: ${{ github.ref_name }}
        
