name: Multi Architecture Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [amd64, 386]
        include:
          - arch: 386
            arch-name: x86
          - arch: amd64
            arch-name: x64

    env:
      GOOS: windows
      GOARCH: ${{ matrix.arch }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v6
        with:
          go-version: '1.24'

      - name: Make Windows (${{ matrix.arch-name }}) Build
        run: go build -o .\dist\relatorioLegado

      - name: Upload Artifact Windows (${{ matrix.arch-name }})
        uses:
          actions/upload-artifact@v4
        with:
          name: WindowsBuild-${{ matrix.arch-name }}
          path: dist\windowsBuild${{ matrix.arch-name }}.exe
        
