name: Multi Architecture Build and Release

on:
  push:
    tags: ["v*"]

jobs:
  windows:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [amd64, 386]
        include:
          - arch: 386
            arch-name: x86
          - arch: amd64
            arch-name: x64

    env:
      GOOS: windows
      GOARCH: ${{ matrix.arch }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v6
        with:
          go-version: "1.24"

      - name: Make Windows (${{ matrix.arch-name }}) Build
        run: go build -ldflags="-H windowsgui" -o .\dist\windowsBuild${{ matrix.arch-name }}.exe

      - name: Upload Artifact Windows (${{ matrix.arch-name }})
        uses: actions/upload-artifact@v4
        with:
          name: WindowsBuild-${{ matrix.arch-name }}
          path: dist\windowsBuild${{ matrix.arch-name }}.exe

  create-release:
    needs: windows

    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          pattern: "WindowsBuild-*"
          path: "artifact"

      - name: Create Release for Windows
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifact/**/*.exe"
          name: ParseLegacy ${{ github.ref_name }} for Windows
          tag: ${{ github.ref_name }}
